<a href="https://colab.research.google.com/github/LinaMariaCastro/curso-ia-para-economia/blob/main/clases/3_Analisis_y_visualizacion_datos/1_Importacion_Extraccion_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Inteligencia Artificial con Aplicaciones en Economía I**

- 👩‍🏫 **Profesora:** [Lina María Castro](https://www.linkedin.com/in/lina-maria-castro)  
- 📧 **Email:** [lmcastroco@gmail.com](mailto:lmcastroco@gmail.com)  
- 🎓 **Universidad:** Universidad Externado de Colombia - Facultad de Economía

# 🛢️**Métodos de importación y extracción de datos**

En esta clase aprenderás a:

- Importar y extraer datos desde diferentes fuentes:

  - Archivos locales (CSV, Excel, TXT)
  - Archivos en la web (CSV desde URL)
  - APIs

- Explorar el dataset

Este es el primer paso para todo análisis de datos en economía y ciencias sociales.

## Instalaciones necesarias

No es necesario si:
- Instalaste los programas del archivo requirements.txt
- Corriste el notebook "0_instalacion_librerias.ipynb"
- Estás usando Google Colab

In [ ]:
# Para poder leer y abrir archivos de Excel
!pip install xlrd openpyxl

In [ ]:
# Para trabajar datos tabulares
!pip install pandas

## Importar librerías

In [12]:
import numpy as np
import pandas as pd

## Mejorar visualización de los dataframes

In [13]:
# Que muestre todas las columnas
pd.options.display.max_columns = None
# En los dataframes, mostrar los float con dos decimales
pd.options.display.float_format = '{:,.2f}'.format

## Importar datos desde archivos CSV, Excel, TXT

En Google Colab hay dos opciones:
- Subir el archivo al entorno (se borra cuando se desconecta del entorno de ejecución o se cierra el notebook)
- Importar el archivo desde Google Drive

### Subir el archivo al entorno

In [ ]:
# Archivo csv
df_ssc = pd.read_csv('Supersociedades_2023.csv', encoding ='utf-8', dtype=str) #latin-1
df_ssc.head()

In [ ]:
df_ssc['ACTIVOS_2023'].dtype

In [ ]:
df_ssc['ACTIVOS_2023'] = df_ssc['ACTIVOS_2023'].astype('float64')
df_ssc.head()

In [ ]:
df_ssc['ACTIVOS_2023'].dtype

In [ ]:
df_ssc['ACTIVOS_2023'] = df_ssc['ACTIVOS_2023'].astype(str)
df_ssc.head()

In [ ]:
df_ssc['ACTIVOS_2023'].dtype

In [ ]:
# Archivo txt
df_mun = pd.read_csv('Base_municipios.txt', sep="|", decimal=',', encoding ='utf-8', converters={'Cod. Municipio':str})
df_mun.head()

In [ ]:
df_mun2 = pd.read_csv('Base_municipios.txt', sep="|", decimal=',', encoding ='utf-8')
df_mun2.head()

In [ ]:
# Archivo Excel
df_divipola_depto = pd.read_excel("2025-01-14 DIVIPOLA.xlsx",
                            sheet_name="Departamentos",
                            skiprows=9)
df_divipola_depto.head()

In [ ]:
# Archivo Excel
df_divipola_mun = pd.read_excel("2025-01-14 DIVIPOLA.xlsx",
                            sheet_name="Municipios",
                            skiprows=10, dtype=str)
df_divipola_mun.head()

In [ ]:
# Renombrar las columnas
df_divipola_mun.rename(columns={'Código':'Cod. Depto',
                                'Nombre': 'Departamento',
                                'Código .1':'Cod. Municipio',
                                'Nombre.1': 'Municipio',
                                'Unnamed: 4': 'Tipo',
                                'Unnamed: 5': 'Area Metropolitana'},
                       inplace=True)
df_divipola_mun.head(6)

### Importar el archivo desde Google Drive

In [11]:
import os

📌 Librería `os` en Python – Comandos más usados

La librería "os" conecta Python con el sistema operativo para manipular archivos, directorios y configuraciones.  

| Comando | Descripción | Ejemplo |
|---------|-------------|---------|
| `os.getcwd()` | Devuelve el directorio de trabajo actual. | `os.getcwd()` |
| `os.listdir(ruta)` | Lista los archivos y carpetas de una ruta. | `os.listdir(".")` |
| `os.chdir(ruta)` | Cambia el directorio de trabajo. | `os.chdir("C:/Users")` |
| `os.mkdir(nombre)` | Crea una nueva carpeta. | `os.mkdir("datos")` |
| `os.makedirs(ruta)` | Crea carpetas anidadas. | `os.makedirs("carpeta1/carpeta2")` |
| `os.remove(archivo)` | Elimina un archivo. | `os.remove("archivo.txt")` |
| `os.rmdir(carpeta)` | Elimina una carpeta vacía. | `os.rmdir("datos")` |
| `os.rename(src, dst)` | Renombra o mueve un archivo/carpeta. | `os.rename("a.txt","b.txt")` |
| `os.path.exists(ruta)` | Verifica si una ruta existe. | `os.path.exists("datos")` |
| `os.path.join(a, b)` | Une rutas de forma segura. | `os.path.join("carpeta", "archivo.csv")` |


⚠️ **Nota:**  
`os.remove` y `os.rmdir` no envían a la papelera, eliminan de forma permanente.

In [11]:
from google.colab import drive, files
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [19]:
path = '/content/drive/MyDrive/bases ia'

In [24]:
# Para establecer el directorio de los archivos
os.chdir(path)

In [28]:
df_mun_drive = pd.read_csv('Copia de Base_municipios', sep="|", decimal=',', encoding ='utf-8', converters={'Cod. Municipio':str})
df_mun_drive.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Copia de Base_municipios'

## Importar datos desde una URL

In [ ]:
# CSV desde URL
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df_url = pd.read_csv(url)
df_url.head()

## Conectarse a una API

- API significa Application Programming Interface o Interfaz de Programación de Aplicaciones.

- Es un conjunto de reglas y herramientas que permite que dos aplicaciones se comuniquen entre sí.

- Una aplicación expone sus funcionalidades o datos a través de la API.

- Otra aplicación puede usarlos, sin necesidad de saber cómo funciona internamente.

- Una API es como un puente que permite a diferentes programas hablar entre sí y compartir información de manera segura y estandarizada.

### Conexión a datos del Banco Mundial (usando wbdata)

El Banco Mundial tiene una API que expone datos de desarrollo económico y social. En Python podemos usar la librería **wbdata**.

Documentación: https://wbdata.readthedocs.io/en/stable/

También se puede utilizar: **wbgapi**

Documentación: https://pypi.org/project/wbgapi/

In [2]:
!pip install wbdata

Requirement already satisfied: wbdata in /usr/local/lib/python3.12/dist-packages (1.1.0)
Requirement already satisfied: appdirs<2,>=1.4 in /usr/local/lib/python3.12/dist-packages (from wbdata) (1.4.4)
Requirement already satisfied: backoff<3,>=2.2.1 in /usr/local/lib/python3.12/dist-packages (from wbdata) (2.2.1)
Requirement already satisfied: cachetools<6,>=5.3.2 in /usr/local/lib/python3.12/dist-packages (from wbdata) (5.5.2)
Requirement already satisfied: dateparser<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from wbdata) (1.3.0)
Requirement already satisfied: decorator<6,>=5.1.1 in /usr/local/lib/python3.12/dist-packages (from wbdata) (5.2.1)
Requirement already satisfied: requests<3,>=2.0 in /usr/local/lib/python3.12/dist-packages (from wbdata) (2.32.4)
Requirement already satisfied: shelved-cache<0.4,>=0.3.1 in /usr/local/lib/python3.12/dist-packages (from wbdata) (0.3.1)
Requirement already satisfied: tabulate<1,>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from wbdata) (0.9.0)
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2.9.0.post0)
Requirement already satisfied: pytz>=2024.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2025.2)
Requirement already satisfied: regex>=2024.9.11 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2025.11.3)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (5.3.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7.0->dateparser<2,>=1.2.0->wbdata) (1.17.0)

In [1]:
import wbdata
import datetime

Nota: "datetime" permite trabajar con fechas y horas.

- Obtener la fecha y hora actual.
- Crear objetos de fecha (año, mes, día).
- Realizar operaciones con fechas (sumar o restar días, calcular diferencias).
- Dar formato a fechas (por ejemplo, mostrar como "31-08-2025" en lugar de "2025-08-31").

El constructor datetime.datetime() acepta argumentos de fecha y hora en el siguiente orden:

datetime.datetime(year, month, day, hour=0, minute=0, second=0, microsecond=0)

hour: Hora (0-23)

minute: Minuto (0-59)

second: Segundo (0-59)

microsecond: Microsegundo (0-999999)

Si no se especifica la hora, minuto o segundo, Python los establecerá en 0 por defecto.

Vamos a traer el PIB per cápita de Colombia entre 2010 y 2023 directamente desde el Banco Mundial.

In [3]:
# Indicador: PIB per cápita (en USD actuales)
# País: Colombia (COL)
indicador = {"NY.GDP.PCAP.CD": "PIB per cápita"}

# El orden es: año (2010), mes (1), día (1)
fecha_inicio = datetime.datetime(2010, 1, 1)
# El orden es: año (2023), mes (1), día (1)
fecha_fin = datetime.datetime(2023, 1, 1)

# Descargar datos
df = wbdata.get_dataframe(indicador, country="COL", date=(fecha_inicio, fecha_fin))

df

      PIB per cápita
date
2023     7000.836605
2022     6680.445069
2021     6222.621644
2020     5339.687114
2019     6472.545449
2018     6816.968183
2017     6479.532313
2016     5959.842504
2015     6248.514905
2014     8187.208249
2013     8279.102556
2012     8108.598382
2011     7400.994070
2010     6398.295845

### Conexión a datos abiertos de Colombia

https://www.datos.gov.co/

#### Ejemplos

1. MEN_ESTADISTICAS_EN_EDUCACION_EN_PREESCOLAR, BÁSICA Y MEDIA_POR_DEPARTAMENTO

https://www.datos.gov.co/Educaci-n/MEN_ESTADISTICAS_EN_EDUCACION_EN_PREESCOLAR-B-SICA/ji8i-4anb/about_data

Ir a Exportar --> API de acceso y copiar el endpoint solamente.

In [4]:
import requests

"requests" es una librería que permite hacer peticiones HTTP (GET, POST, PUT, DELETE) de manera sencilla.

GET → traer datos desde una página o API.

POST → enviar datos a un servidor.

In [14]:


url = "https://www.datos.gov.co/resource/ji8i-4anb.json"

# Solicitud a la API
response = requests.get(url)
data = response.json()

# Convertir a DataFrame
df = pd.DataFrame(data)

df.head()

,ano,c_digo_departamento,departamento,poblacion_5_16,tasa_matriculacion_5_16,cobertura_neta,cobertura_neta_transicion,cobertura_neta_primaria,cobertura_neta_secundaria,cobertura_neta_media,cobertura_bruta,cobertura_bruta_transicion,cobertura_bruta_primaria,cobertura_bruta_secundaria,cobertura_bruta_media,tamano_promedio_grupo,sedes_conectadas_a_internet,desercion,desercion_transicion,desercion_primaria,desercion_secundaria,desercion_media,aprobacion,aprobacion_transicion,aprobacion_primaria,aprobacion_secundaria,aprobacion_media,reprobacion,reprobacion_transicion,reprobacion_primaria,reprobacion_secundaria,reprobacion_media,repitencia,repitencia_transicion,repitencia_primaria,repitencia_secundaria,repitencia_media
0,2011,5,Antioquia,1288473,94.01,93.85,70.28,94.12,75.68,44.37,106.81,85.69,117.5,110.81,84.06,27.47,74.48,3.97,3.62,3.65,4.57,3.71,93.98,0.07,94.56,4.57,93.33,2.06,0.07,94.56,2.54,2.96,4.25,0.07,4.56,5.27,1.68
1,2011,8,Atlántico,523935,99.32,99.05,50.59,98.93,80.22,50.17,107.88,84.19,120.41,107.89,87.98,24.42,80.46,2.76,2.6,3.06,2.42,2.61,96.7,0.12,96.49,2.42,96.64,0.54,0.12,96.49,0.67,0.75,1.82,0.12,1.77,2.18,0.88
2,2011,11,"Bogotá, D.C.",1479334,90.7,90.29,68.63,86.99,84.7,55.01,97.78,82.04,97.94,106.48,87.76,26.75,94.21,3.95,10.05,5.3,1.96,2.55,96.05,0,94.69,1.96,97.45,0,0,94.69,0,0,3.23,0,2.3,5.11,2.57
3,2011,13,Bolívar,496676,91.57,91.4,59.74,90.81,67.34,39.17,110.41,98.82,126.45,108.15,80.64,20.8,30.12,3.14,1.85,2.93,3.79,3.13,94.76,0.46,95.48,3.79,93.2,2.1,0.46,95.48,2.75,3.67,4.43,0.46,4.44,5.37,2.28
4,2011,15,Boyacá,300501,86.16,86.11,63.36,82.5,74.65,49.09,104.15,78.87,99.88,119.78,94.76,22.77,25.26,3.07,2.4,2.24,4.03,3.51,94.2,0.17,96.1,4.03,93.23,2.73,0.17,96.1,4.31,3.26,2.62,0.17,1.9,4.19,1.55

2. Casos positivos de COVID-19 en Colombia

In [15]:
url = "https://www.datos.gov.co/resource/gt2j-8ykr.json"

# Solicitud a la API
response = requests.get(url)
data = response.json()

# Convertir a DataFrame
df = pd.DataFrame(data)

df.head()

,fecha_reporte_web,id_de_caso,fecha_de_notificaci_n,departamento,departamento_nom,ciudad_municipio,ciudad_municipio_nom,edad,unidad_medida,sexo,fuente_tipo_contagio,ubicacion,estado,recuperado,fecha_inicio_sintomas,fecha_diagnostico,fecha_recuperado,tipo_recuperacion,per_etn_,fecha_muerte,nom_grupo_
0,2020-12-24 00:00:00,1556979,2020-12-22 00:00:00,76,VALLE,76001,CALI,67,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-21 00:00:00,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN,NaN
1,2020-12-24 00:00:00,1556980,2020-12-19 00:00:00,76,VALLE,76001,CALI,66,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-07 00:00:00,2020-12-23 00:00:00,2020-12-25 00:00:00,Tiempo,6,NaN,NaN
2,2020-12-24 00:00:00,1556981,2020-12-19 00:00:00,76,VALLE,76001,CALI,68,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-18 00:00:00,2020-12-22 00:00:00,2021-01-01 00:00:00,Tiempo,6,NaN,NaN
3,2020-12-24 00:00:00,1556982,2020-12-22 00:00:00,76,VALLE,76001,CALI,74,1,F,Comunitaria,Fallecido,Fallecido,Fallecido,2020-12-17 00:00:00,2020-12-23 00:00:00,NaN,NaN,6,2020-12-30 00:00:00,NaN
4,2020-12-24 00:00:00,1556983,2020-12-22 00:00:00,76,VALLE,76001,CALI,65,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-21 00:00:00,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN,NaN

## Explorar el dataset

In [16]:
df

,fecha_reporte_web,id_de_caso,fecha_de_notificaci_n,departamento,departamento_nom,ciudad_municipio,ciudad_municipio_nom,edad,unidad_medida,sexo,fuente_tipo_contagio,ubicacion,estado,recuperado,fecha_inicio_sintomas,fecha_diagnostico,fecha_recuperado,tipo_recuperacion,per_etn_,fecha_muerte,nom_grupo_
0,2020-12-24 00:00:00,1556979,2020-12-22 00:00:00,76,VALLE,76001,CALI,67,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-21 00:00:00,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN,NaN
1,2020-12-24 00:00:00,1556980,2020-12-19 00:00:00,76,VALLE,76001,CALI,66,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-07 00:00:00,2020-12-23 00:00:00,2020-12-25 00:00:00,Tiempo,6,NaN,NaN
2,2020-12-24 00:00:00,1556981,2020-12-19 00:00:00,76,VALLE,76001,CALI,68,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-18 00:00:00,2020-12-22 00:00:00,2021-01-01 00:00:00,Tiempo,6,NaN,NaN
3,2020-12-24 00:00:00,1556982,2020-12-22 00:00:00,76,VALLE,76001,CALI,74,1,F,Comunitaria,Fallecido,Fallecido,Fallecido,2020-12-17 00:00:00,2020-12-23 00:00:00,NaN,NaN,6,2020-12-30 00:00:00,NaN
4,2020-12-24 00:00:00,1556983,2020-12-22 00:00:00,76,VALLE,76001,CALI,65,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-21 00:00:00,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2020-09-03 00:00:00,640273,2020-08-11 00:00:00,5,ANTIOQUIA,5088,BELLO,37,1,F,Comunitaria,Casa,Leve,Recuperado,2020-08-07 00:00:00,2020-08-22 00:00:00,2020-09-04 00:00:00,Tiempo,6,NaN,NaN
996,2020-09-03 00:00:00,640274,2020-08-13 00:00:00,68,SANTANDER,68081,BARRANCABERMEJA,12,1,F,Comunitaria,Casa,Leve,Recuperado,2020-08-08 00:00:00,2020-08-24 00:00:00,2020-09-04 00:00:00,Tiempo,6,NaN,NaN
997,2020-09-03 00:00:00,640275,2020-08-13 00:00:00,68,SANTANDER,68081,BARRANCABERMEJA,11,1,M,Comunitaria,Casa,Leve,Recuperado,2020-08-08 00:00:00,2020-08-24 00:00:00,2020-09-04 00:00:00,Tiempo,6,NaN,NaN
998,2020-09-03 00:00:00,640276,2020-08-13 00:00:00,68,SANTANDER,68081,BARRANCABERMEJA,6,1,F,Comunitaria,Casa,Leve,Recuperado,2020-08-08 00:00:00,2020-08-24 00:00:00,2020-09-04 00:00:00,Tiempo,6,NaN,NaN
999,2020-09-03 00:00:00,640277,2020-08-14 00:00:00,5,ANTIOQUIA,5088,BELLO,31,1,M,Comunitaria,Casa,Leve,Recuperado,2020-08-10 00:00:00,2020-08-25 00:00:00,2020-09-04 00:00:00,Tiempo,6,NaN,NaN

In [17]:
df.head()

,fecha_reporte_web,id_de_caso,fecha_de_notificaci_n,departamento,departamento_nom,ciudad_municipio,ciudad_municipio_nom,edad,unidad_medida,sexo,fuente_tipo_contagio,ubicacion,estado,recuperado,fecha_inicio_sintomas,fecha_diagnostico,fecha_recuperado,tipo_recuperacion,per_etn_,fecha_muerte,nom_grupo_
0,2020-12-24 00:00:00,1556979,2020-12-22 00:00:00,76,VALLE,76001,CALI,67,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-21 00:00:00,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN,NaN
1,2020-12-24 00:00:00,1556980,2020-12-19 00:00:00,76,VALLE,76001,CALI,66,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-07 00:00:00,2020-12-23 00:00:00,2020-12-25 00:00:00,Tiempo,6,NaN,NaN
2,2020-12-24 00:00:00,1556981,2020-12-19 00:00:00,76,VALLE,76001,CALI,68,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-18 00:00:00,2020-12-22 00:00:00,2021-01-01 00:00:00,Tiempo,6,NaN,NaN
3,2020-12-24 00:00:00,1556982,2020-12-22 00:00:00,76,VALLE,76001,CALI,74,1,F,Comunitaria,Fallecido,Fallecido,Fallecido,2020-12-17 00:00:00,2020-12-23 00:00:00,NaN,NaN,6,2020-12-30 00:00:00,NaN
4,2020-12-24 00:00:00,1556983,2020-12-22 00:00:00,76,VALLE,76001,CALI,65,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-21 00:00:00,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN,NaN

In [18]:
df.head(2)

,fecha_reporte_web,id_de_caso,fecha_de_notificaci_n,departamento,departamento_nom,ciudad_municipio,ciudad_municipio_nom,edad,unidad_medida,sexo,fuente_tipo_contagio,ubicacion,estado,recuperado,fecha_inicio_sintomas,fecha_diagnostico,fecha_recuperado,tipo_recuperacion,per_etn_,fecha_muerte,nom_grupo_
0,2020-12-24 00:00:00,1556979,2020-12-22 00:00:00,76,VALLE,76001,CALI,67,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-21 00:00:00,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN,NaN
1,2020-12-24 00:00:00,1556980,2020-12-19 00:00:00,76,VALLE,76001,CALI,66,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-07 00:00:00,2020-12-23 00:00:00,2020-12-25 00:00:00,Tiempo,6,NaN,NaN

In [19]:
df.head(10)

,fecha_reporte_web,id_de_caso,fecha_de_notificaci_n,departamento,departamento_nom,ciudad_municipio,ciudad_municipio_nom,edad,unidad_medida,sexo,fuente_tipo_contagio,ubicacion,estado,recuperado,fecha_inicio_sintomas,fecha_diagnostico,fecha_recuperado,tipo_recuperacion,per_etn_,fecha_muerte,nom_grupo_
0,2020-12-24 00:00:00,1556979,2020-12-22 00:00:00,76,VALLE,76001,CALI,67,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-21 00:00:00,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN,NaN
1,2020-12-24 00:00:00,1556980,2020-12-19 00:00:00,76,VALLE,76001,CALI,66,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-07 00:00:00,2020-12-23 00:00:00,2020-12-25 00:00:00,Tiempo,6,NaN,NaN
2,2020-12-24 00:00:00,1556981,2020-12-19 00:00:00,76,VALLE,76001,CALI,68,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-18 00:00:00,2020-12-22 00:00:00,2021-01-01 00:00:00,Tiempo,6,NaN,NaN
3,2020-12-24 00:00:00,1556982,2020-12-22 00:00:00,76,VALLE,76001,CALI,74,1,F,Comunitaria,Fallecido,Fallecido,Fallecido,2020-12-17 00:00:00,2020-12-23 00:00:00,NaN,NaN,6,2020-12-30 00:00:00,NaN
4,2020-12-24 00:00:00,1556983,2020-12-22 00:00:00,76,VALLE,76001,CALI,65,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-21 00:00:00,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN,NaN
5,2020-12-24 00:00:00,1556984,2020-12-15 00:00:00,76,VALLE,76001,CALI,66,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-09 00:00:00,2020-12-23 00:00:00,2020-12-25 00:00:00,Tiempo,6,NaN,NaN
6,2020-12-24 00:00:00,1556985,2020-12-21 00:00:00,76,VALLE,76001,CALI,74,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-14 00:00:00,2020-12-22 00:00:00,2020-12-28 00:00:00,Tiempo,6,NaN,NaN
7,2020-12-24 00:00:00,1556986,2020-12-18 00:00:00,76,VALLE,76001,CALI,66,1,F,Comunitaria,Fallecido,Fallecido,Fallecido,2020-12-11 00:00:00,2020-12-22 00:00:00,NaN,NaN,6,2020-12-26 00:00:00,NaN
8,2020-12-24 00:00:00,1556987,2020-12-18 00:00:00,76,VALLE,76001,CALI,64,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-15 00:00:00,2020-12-23 00:00:00,2020-12-30 00:00:00,Tiempo,6,NaN,NaN
9,2020-12-24 00:00:00,1556988,2020-12-17 00:00:00,76,VALLE,76001,CALI,65,1,F,Comunitaria,Casa,Leve,Recuperado,2020-12-08 00:00:00,2020-12-22 00:00:00,2020-12-25 00:00:00,Tiempo,6,NaN,NaN

In [20]:
df.tail(2)

,fecha_reporte_web,id_de_caso,fecha_de_notificaci_n,departamento,departamento_nom,ciudad_municipio,ciudad_municipio_nom,edad,unidad_medida,sexo,fuente_tipo_contagio,ubicacion,estado,recuperado,fecha_inicio_sintomas,fecha_diagnostico,fecha_recuperado,tipo_recuperacion,per_etn_,fecha_muerte,nom_grupo_
998,2020-09-03 00:00:00,640276,2020-08-13 00:00:00,68,SANTANDER,68081,BARRANCABERMEJA,6,1,F,Comunitaria,Casa,Leve,Recuperado,2020-08-08 00:00:00,2020-08-24 00:00:00,2020-09-04 00:00:00,Tiempo,6,NaN,NaN
999,2020-09-03 00:00:00,640277,2020-08-14 00:00:00,5,ANTIOQUIA,5088,BELLO,31,1,M,Comunitaria,Casa,Leve,Recuperado,2020-08-10 00:00:00,2020-08-25 00:00:00,2020-09-04 00:00:00,Tiempo,6,NaN,NaN

In [21]:
df.sample()

,fecha_reporte_web,id_de_caso,fecha_de_notificaci_n,departamento,departamento_nom,ciudad_municipio,ciudad_municipio_nom,edad,unidad_medida,sexo,fuente_tipo_contagio,ubicacion,estado,recuperado,fecha_inicio_sintomas,fecha_diagnostico,fecha_recuperado,tipo_recuperacion,per_etn_,fecha_muerte,nom_grupo_
574,2020-07-18 00:00:00,187634,2020-07-01 00:00:00,8001,BARRANQUILLA,8001,BARRANQUILLA,29,1,M,Comunitaria,Casa,Leve,Recuperado,2020-06-28 00:00:00,2020-07-12 00:00:00,2020-07-27 00:00:00,Tiempo,6,NaN,NaN

In [22]:
df.sample(3)

,fecha_reporte_web,id_de_caso,fecha_de_notificaci_n,departamento,departamento_nom,ciudad_municipio,ciudad_municipio_nom,edad,unidad_medida,sexo,fuente_tipo_contagio,ubicacion,estado,recuperado,fecha_inicio_sintomas,fecha_diagnostico,fecha_recuperado,tipo_recuperacion,per_etn_,fecha_muerte,nom_grupo_
35,2020-11-08 00:00:00,1137445,2020-11-03 00:00:00,66,RISARALDA,66682,SANTA ROSA DE CABAL,40,1,F,Comunitaria,Casa,Leve,Recuperado,2020-10-31 00:00:00,2020-11-07 00:00:00,2020-11-15 00:00:00,Tiempo,6,NaN,NaN
511,2020-09-03 00:00:00,640713,2020-08-21 00:00:00,5,ANTIOQUIA,5088,BELLO,62,1,M,Relacionado,Casa,Leve,Recuperado,2020-08-17 00:00:00,2020-09-01 00:00:00,2020-09-08 00:00:00,Tiempo,6,NaN,NaN
834,2020-06-25 00:00:00,78509,2020-06-19 00:00:00,70,SUCRE,70001,SINCELEJO,31,1,M,Comunitaria,Casa,Leve,Recuperado,2020-06-19 00:00:00,2020-06-25 00:00:00,2021-03-26 00:00:00,PCR,6,NaN,NaN

In [23]:
# Para ver todas las filas, pero seleccionar ciertas columnas
# Opción 1
df.loc[:,['departamento_nom','edad','fecha_inicio_sintomas']]

    departamento_nom edad fecha_inicio_sintomas
0              VALLE   67   2020-12-21 00:00:00
1              VALLE   66   2020-12-07 00:00:00
2              VALLE   68   2020-12-18 00:00:00
3              VALLE   74   2020-12-17 00:00:00
4              VALLE   65   2020-12-21 00:00:00
..               ...  ...                   ...
995        ANTIOQUIA   37   2020-08-07 00:00:00
996        SANTANDER   12   2020-08-08 00:00:00
997        SANTANDER   11   2020-08-08 00:00:00
998        SANTANDER    6   2020-08-08 00:00:00
999        ANTIOQUIA   31   2020-08-10 00:00:00

[1000 rows x 3 columns]

In [24]:
df.loc[500:504,['departamento_nom','edad','fecha_inicio_sintomas']]

    departamento_nom edad fecha_inicio_sintomas
500     BARRANQUILLA   25   2020-06-27 00:00:00
501     BARRANQUILLA   65   2020-06-27 00:00:00
502     BARRANQUILLA   77   2020-06-26 00:00:00
503     BARRANQUILLA   43   2020-06-26 00:00:00
504   STA MARTA D.E.   39   2020-06-25 00:00:00

In [25]:
# Opción 2: solo seleccionar las columnas que quiero ver
df[['departamento_nom','edad','fecha_inicio_sintomas']]

    departamento_nom edad fecha_inicio_sintomas
0              VALLE   67   2020-12-21 00:00:00
1              VALLE   66   2020-12-07 00:00:00
2              VALLE   68   2020-12-18 00:00:00
3              VALLE   74   2020-12-17 00:00:00
4              VALLE   65   2020-12-21 00:00:00
..               ...  ...                   ...
995        ANTIOQUIA   37   2020-08-07 00:00:00
996        SANTANDER   12   2020-08-08 00:00:00
997        SANTANDER   11   2020-08-08 00:00:00
998        SANTANDER    6   2020-08-08 00:00:00
999        ANTIOQUIA   31   2020-08-10 00:00:00

[1000 rows x 3 columns]

In [26]:
# Puedo crear un nuevo dataframe con las columnas que necesito solamente
df2 = df[['departamento_nom','edad','fecha_inicio_sintomas']].copy()
df2

    departamento_nom edad fecha_inicio_sintomas
0              VALLE   67   2020-12-21 00:00:00
1              VALLE   66   2020-12-07 00:00:00
2              VALLE   68   2020-12-18 00:00:00
3              VALLE   74   2020-12-17 00:00:00
4              VALLE   65   2020-12-21 00:00:00
..               ...  ...                   ...
995        ANTIOQUIA   37   2020-08-07 00:00:00
996        SANTANDER   12   2020-08-08 00:00:00
997        SANTANDER   11   2020-08-08 00:00:00
998        SANTANDER    6   2020-08-08 00:00:00
999        ANTIOQUIA   31   2020-08-10 00:00:00

[1000 rows x 3 columns]

In [ ]:
# Ver el nombre de todas las columnas
df.columns

In [ ]:
df2.columns

In [ ]:
# Ver los tipos de datos de cada columna
df2.dtypes

In [ ]:
# Ver la cantidad de filas del df
len(df2)

In [ ]:
# Ver la cantidad de filas y columnas del df
df2.shape

In [27]:
# Ver la cantidad de filas y columnas, el nombre todas las columnas, el tipo de datos y si tiene nulos
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   departamento_nom       1000 non-null   object
 1   edad                   1000 non-null   object
 2   fecha_inicio_sintomas  985 non-null    object
dtypes: object(3)
memory usage: 23.6+ KB